export const FRANCE = [
  {
    department: 'Ain',
    department_value: '01',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Aisne',
    department_value: '02',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Allier',
    department_value: '03',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Alpes de Haute-Provence',
    department_value: '04',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Hautes-Alpes',
    department_value: '05',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Alpes-Maritimes',
    department_value: '06',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Ardèche',
    department_value: '07',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Ardennes',
    department_value: '08',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Ariège',
    department_value: '09',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Aube',
    department_value: '10',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Aude',
    department_value: '11',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Aveyron',
    department_value: '12',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Bouches-du-Rhône',
    department_value: '13',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Calvados',
    department_value: '14',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Cantal',
    department_value: '15',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Charente',
    department_value: '16',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Charente-Maritime',
    department_value: '17',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Cher',
    department_value: '18',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Corrèze',
    department_value: '19',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Corse-du-Sud',
    department_value: '2A',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Haute-Corse',
    department_value: '2B',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Côte-d’Or',
    department_value: '21',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Côtes d’Armor',
    department_value: '22',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Creuse',
    department_value: '23',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Dordogne',
    department_value: '24',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Doubs',
    department_value: '25',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Drôme',
    department_value: '26',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Eure',
    department_value: '27',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Eure-et-Loir',
    department_value: '28',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Finistère',
    department_value: '29',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Gard',
    department_value: '30',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Haute-Garonne',
    department_value: '31',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gers',
    department_value: '32',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gironde',
    department_value: '33',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hérault',
    department_value: '34',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Ille-et-Vilaine',
    department_value: '35',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Indre',
    department_value: '36',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Indre-et-Loire',
    department_value: '37',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Isère',
    department_value: '38',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Jura',
    department_value: '39',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Landes',
    department_value: '40',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Loir-et-Cher',
    department_value: '41',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Loire',
    department_value: '42',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Loire',
    department_value: '43',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Loire-Atlantique',
    department_value: '44',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Loiret',
    department_value: '45',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Lot',
    department_value: '46',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Lot-et-Garonne',
    department_value: '47',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Lozère',
    department_value: '48',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Maine-et-Loire',
    department_value: '49',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Manche',
    department_value: '50',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Marne',
    department_value: '51',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Haute-Marne',
    department_value: '52',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Mayenne',
    department_value: '53',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Meurthe-et-Moselle',
    department_value: '54',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Meuse',
    department_value: '55',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Morbihan',
    department_value: '56',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Moselle',
    department_value: '57',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Nièvre',
    department_value: '58',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Nord',
    department_value: '59',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Oise',
    department_value: '60',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Orne',
    department_value: '61',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Pas-de-Calais',
    department_value: '62',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Puy-de-Dôme',
    department_value: '63',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Pyrénées-Atlantiques',
    department_value: '64',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hautes-Pyrénées',
    department_value: '65',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Pyrénées-Orientales',
    department_value: '66',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Bas-Rhin',
    department_value: '67',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Haut-Rhin',
    department_value: '68',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Rhône',
    department_value: '69',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Saône',
    department_value: '70',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Saône-et-Loire',
    department_value: '71',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Sarthe',
    department_value: '72',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Savoie',
    department_value: '73',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Haute-Savoie',
    department_value: '74',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Paris',
    department_value: '75',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Paris',
    academy_value: 'PARIS',
  },
  {
    department: 'Seine-Maritime',
    department_value: '76',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Seine-et-Marne',
    department_value: '77',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Yvelines',
    department_value: '78',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Deux-Sèvres',
    department_value: '79',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Somme',
    department_value: '80',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Tarn',
    department_value: '81',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Tarn-et-Garonne',
    department_value: '82',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Var',
    department_value: '83',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Vaucluse',
    department_value: '84',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Vendée',
    department_value: '85',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Vienne',
    department_value: '86',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Haute-Vienne',
    department_value: '87',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Vosges',
    department_value: '88',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Yonne',
    department_value: '89',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Territoire-de-Belfort',
    department_value: '90',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Essonne',
    department_value: '91',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Hauts-de-Seine',
    department_value: '92',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Seine-Saint-Denis',
    department_value: '93',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-de-Marne',
    department_value: '94',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-d’Oise',
    department_value: '95',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Guadeloupe',
    department_value: '971',
    region: 'Guadeloupe',
    region_value: '971',
    academy: 'Académie de Guadeloupe',
    academy_value: 'GUADELOUPE',
  },
  {
    department: 'Martinique',
    department_value: '972',
    region: 'Martinique',
    region_value: '972',
    academy: 'Académie de Martinique',
    academy_value: 'MARTINIQUE',
  },
  {
    department: 'Guyane française',
    department_value: '973',
    region: 'Guyane',
    region_value: '973',
    academy: 'Académie de Guyane',
    academy_value: 'GUYANE',
  },
  {
    department: 'La Réunion',
    department_value: '974',
    region: 'La Réunion',
    region_value: '974',
    academy: 'Académie de La Réunion',
    academy_value: 'REUNION',
  },
  {
    department: 'Mayotte',
    department_value: '976',
    region: 'Mayotte',
    region_value: '976',
    academy: 'Académie de Mayotte',
    academy_value: 'MAYOTTE',
  },
];
