export const FRANCE = [
  {
    department: 'Ain',
    department_value: '01',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Aisne',
    department_value: '02',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Allier',
    department_value: '03',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Alpes de Haute-Provence',
    department_value: '04',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Hautes-Alpes',
    department_value: '05',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Alpes-Maritimes',
    department_value: '06',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Ardèche',
    department_value: '07',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Ardennes',
    department_value: '08',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Ariège',
    department_value: '09',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Aube',
    department_value: '10',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Aude',
    department_value: '11',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Aveyron',
    department_value: '12',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Bouches-du-Rhône',
    department_value: '13',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Calvados',
    department_value: '14',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Cantal',
    department_value: '15',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Charente',
    department_value: '16',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Charente-Maritime',
    department_value: '17',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Cher',
    department_value: '18',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Corrèze',
    department_value: '19',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Corse-du-Sud',
    department_value: '2A',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Haute-Corse',
    department_value: '2B',
    region: 'Corse',
    region_value: '20R',
    academy: 'Académie de Corse',
    academy_value: 'CORSE',
  },
  {
    department: 'Côte-d’Or',
    department_value: '21',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Côtes d’Armor',
    department_value: '22',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Creuse',
    department_value: '23',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Dordogne',
    department_value: '24',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Doubs',
    department_value: '25',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Drôme',
    department_value: '26',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Eure',
    department_value: '27',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Eure-et-Loir',
    department_value: '28',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Finistère',
    department_value: '29',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Gard',
    department_value: '30',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Haute-Garonne',
    department_value: '31',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gers',
    department_value: '32',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Gironde',
    department_value: '33',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hérault',
    department_value: '34',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Ille-et-Vilaine',
    department_value: '35',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Indre',
    department_value: '36',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Indre-et-Loire',
    department_value: '37',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Isère',
    department_value: '38',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Jura',
    department_value: '39',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Landes',
    department_value: '40',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Loir-et-Cher',
    department_value: '41',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Loire',
    department_value: '42',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Loire',
    department_value: '43',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Loire-Atlantique',
    department_value: '44',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Loiret',
    department_value: '45',
    region: 'Centre-Val de Loire',
    region_value: 'CVL',
    academy: 'Académie d’Orléans-Tours',
    academy_value: 'ORLEANS-TOURS',
  },
  {
    department: 'Lot',
    department_value: '46',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Lot-et-Garonne',
    department_value: '47',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Lozère',
    department_value: '48',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Maine-et-Loire',
    department_value: '49',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Manche',
    department_value: '50',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Marne',
    department_value: '51',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Haute-Marne',
    department_value: '52',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Reims',
    academy_value: 'REIMS',
  },
  {
    department: 'Mayenne',
    department_value: '53',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Meurthe-et-Moselle',
    department_value: '54',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Meuse',
    department_value: '55',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Morbihan',
    department_value: '56',
    region: 'Bretagne',
    region_value: 'BRE',
    academy: 'Académie de Rennes',
    academy_value: 'RENNES',
  },
  {
    department: 'Moselle',
    department_value: '57',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Nièvre',
    department_value: '58',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Nord',
    department_value: '59',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Oise',
    department_value: '60',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Orne',
    department_value: '61',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Pas-de-Calais',
    department_value: '62',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie de Lille',
    academy_value: 'LILLE',
  },
  {
    department: 'Puy-de-Dôme',
    department_value: '63',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Clermont-Ferrand',
    academy_value: 'CLERMONT-FERRAND',
  },
  {
    department: 'Pyrénées-Atlantiques',
    department_value: '64',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Bordeaux',
    academy_value: 'BORDEAUX',
  },
  {
    department: 'Hautes-Pyrénées',
    department_value: '65',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Pyrénées-Orientales',
    department_value: '66',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Montpellier',
    academy_value: 'MONTPELLIER',
  },
  {
    department: 'Bas-Rhin',
    department_value: '67',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Haut-Rhin',
    department_value: '68',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Strasbourg',
    academy_value: 'STRASBOURG',
  },
  {
    department: 'Rhône',
    department_value: '69',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Lyon',
    academy_value: 'LYON',
  },
  {
    department: 'Haute-Saône',
    department_value: '70',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Saône-et-Loire',
    department_value: '71',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Sarthe',
    department_value: '72',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Savoie',
    department_value: '73',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Haute-Savoie',
    department_value: '74',
    region: 'Auvergne-Rhône-Alpes',
    region_value: 'ARA',
    academy: 'Académie de Grenoble',
    academy_value: 'GRENOBLE',
  },
  {
    department: 'Paris',
    department_value: '75',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Paris',
    academy_value: 'PARIS',
  },
  {
    department: 'Seine-Maritime',
    department_value: '76',
    region: 'Normandie',
    region_value: 'NOR',
    academy: 'Académie de Normandie',
    academy_value: 'NORMANDIE',
  },
  {
    department: 'Seine-et-Marne',
    department_value: '77',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Yvelines',
    department_value: '78',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Deux-Sèvres',
    department_value: '79',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Somme',
    department_value: '80',
    region: 'Hauts-de-France',
    region_value: 'HDF',
    academy: 'Académie d’Amiens',
    academy_value: 'AMIENS',
  },
  {
    department: 'Tarn',
    department_value: '81',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Tarn-et-Garonne',
    department_value: '82',
    region: 'Occitanie',
    region_value: 'OCC',
    academy: 'Académie de Toulouse',
    academy_value: 'TOULOUSE',
  },
  {
    department: 'Var',
    department_value: '83',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie de Nice',
    academy_value: 'NICE',
  },
  {
    department: 'Vaucluse',
    department_value: '84',
    region: 'Provence-Alpes-Côte d’Azur',
    region_value: 'PAC',
    academy: 'Académie d’Aix-Marseille',
    academy_value: 'AIX-MARSEILLE',
  },
  {
    department: 'Vendée',
    department_value: '85',
    region: 'Pays de la Loire',
    region_value: 'PDL',
    academy: 'Académie de Nantes',
    academy_value: 'NANTES',
  },
  {
    department: 'Vienne',
    department_value: '86',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Poitiers',
    academy_value: 'POITIERS',
  },
  {
    department: 'Haute-Vienne',
    department_value: '87',
    region: 'Nouvelle-Aquitaine',
    region_value: 'NAQ',
    academy: 'Académie de Limoges',
    academy_value: 'LIMOGES',
  },
  {
    department: 'Vosges',
    department_value: '88',
    region: 'Grand Est',
    region_value: 'GES',
    academy: 'Académie de Nancy-Metz',
    academy_value: 'NANCY-METZ',
  },
  {
    department: 'Yonne',
    department_value: '89',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Dijon',
    academy_value: 'DIJON',
  },
  {
    department: 'Territoire-de-Belfort',
    department_value: '90',
    region: 'Bourgogne-Franche-Comté',
    region_value: 'BFC',
    academy: 'Académie de Besançon',
    academy_value: 'BESANCON',
  },
  {
    department: 'Essonne',
    department_value: '91',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Hauts-de-Seine',
    department_value: '92',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Seine-Saint-Denis',
    department_value: '93',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-de-Marne',
    department_value: '94',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Créteil',
    academy_value: 'CRETEIL',
  },
  {
    department: 'Val-d’Oise',
    department_value: '95',
    region: 'Île-de-France',
    region_value: 'IDF',
    academy: 'Académie de Versailles',
    academy_value: 'VERSAILLES',
  },
  {
    department: 'Guadeloupe',
    department_value: '971',
    region: 'Guadeloupe',
    region_value: '971',
    academy: 'Académie de Guadeloupe',
    academy_value: 'GUADELOUPE',
  },
  {
    department: 'Martinique',
    department_value: '972',
    region: 'Martinique',
    region_value: '972',
    academy: 'Académie de Martinique',
    academy_value: 'MARTINIQUE',
  },
  {
    department: 'Guyane française',
    department_value: '973',
    region: 'Guyane',
    region_value: '973',
    academy: 'Académie de Guyane',
    academy_value: 'GUYANE',
  },
  {
    department: 'La Réunion',
    department_value: '974',
    region: 'La Réunion',
    region_value: '974',
    academy: 'Académie de La Réunion',
    academy_value: 'REUNION',
  },
  {
    department: 'Mayotte',
    department_value: '976',
    region: 'Mayotte',
    region_value: '976',
    academy: 'Académie de Mayotte',
    academy_value: 'MAYOTTE',
  },
];

export const WORLD = [
  {
    country: 'United Arab Emirates',
    country_value: 'AE',
  },
  {
    country: 'Afghanistan',
    country_value: 'AF',
  },
  {
    country: 'Albania',
    country_value: 'AL',
  },
  {
    country: 'Armenia',
    country_value: 'AM',
  },
  {
    country: 'Angola',
    country_value: 'AO',
  },
  {
    country: 'Argentina',
    country_value: 'AR',
  },
  {
    country: 'Austria',
    country_value: 'AT',
  },
  {
    country: 'Australia',
    country_value: 'AU',
  },
  {
    country: 'Azerbaijan',
    country_value: 'AZ',
  },
  {
    country: 'Bosnia and Herzegovina',
    country_value: 'BA',
  },
  {
    country: 'Bangladesh',
    country_value: 'BD',
  },
  {
    country: 'Belgium',
    country_value: 'BE',
  },
  {
    country: 'Burkina Faso',
    country_value: 'BF',
  },
  {
    country: 'Bulgaria',
    country_value: 'BG',
  },
  {
    country: 'Burundi',
    country_value: 'BI',
  },
  {
    country: 'Benin',
    country_value: 'BJ',
  },
  {
    country: 'Brunei Darussalam',
    country_value: 'BN',
  },
  {
    country: 'Bolivia',
    country_value: 'BO',
  },
  {
    country: 'Brazil',
    country_value: 'BR',
  },
  {
    country: 'Bahamas',
    country_value: 'BS',
  },
  {
    country: 'Bhutan',
    country_value: 'BT',
  },
  {
    country: 'Botswana',
    country_value: 'BW',
  },
  {
    country: 'Belarus',
    country_value: 'BY',
  },
  {
    country: 'Belize',
    country_value: 'BZ',
  },
  {
    country: 'Canada',
    country_value: 'CA',
  },
  {
    country: 'Democratic Republic of Congo',
    country_value: 'CD',
  },
  {
    country: 'Central African Republic',
    country_value: 'CF',
  },
  {
    country: 'Republic of Congo',
    country_value: 'CG',
  },
  {
    country: 'Switzerland',
    country_value: 'CH',
  },
  {
    country: 'Côte d’Ivoire',
    country_value: 'CI',
  },
  {
    country: 'Chile',
    country_value: 'CL',
  },
  {
    country: 'Cameroon',
    country_value: 'CM',
  },
  {
    country: 'China',
    country_value: 'CN',
  },
  {
    country: 'Colombia',
    country_value: 'CO',
  },
  {
    country: 'Costa Rica',
    country_value: 'CR',
  },
  {
    country: 'Cuba',
    country_value: 'CU',
  },
  {
    country: 'Cyprus',
    country_value: 'CY',
  },
  {
    country: 'Czech Republic',
    country_value: 'CZ',
  },
  {
    country: 'Germany',
    country_value: 'DE',
  },
  {
    country: 'Djibouti',
    country_value: 'DJ',
  },
  {
    country: 'Denmark',
    country_value: 'DK',
  },
  {
    country: 'Dominican Republic',
    country_value: 'DO',
  },
  {
    country: 'Algeria',
    country_value: 'DZ',
  },
  {
    country: 'Ecuador',
    country_value: 'EC',
  },
  {
    country: 'Estonia',
    country_value: 'EE',
  },
  {
    country: 'Egypt',
    country_value: 'EG',
  },
  {
    country: 'Western Sahara',
    country_value: 'EH',
  },
  {
    country: 'Eritrea',
    country_value: 'ER',
  },
  {
    country: 'Spain',
    country_value: 'ES',
  },
  {
    country: 'Ethiopia',
    country_value: 'ET',
  },
  {
    country: 'Finland',
    country_value: 'FI',
  },
  {
    country: 'Fiji',
    country_value: 'FJ',
  },
  {
    country: 'Falkland Islands',
    country_value: 'FK',
  },
  {
    country: 'France',
    country_value: 'FR',
  },
  {
    country: 'Gabon',
    country_value: 'GA',
  },
  {
    country: 'United Kingdom of Great Britain and Northern Ireland',
    country_value: 'GB',
  },
  {
    country: 'Greenland',
    country_value: 'GD',
  },
  {
    country: 'Georgia',
    country_value: 'GE',
  },
  {
    country: 'French Guiana',
    country_value: 'GF',
  },
  {
    country: 'Ghana',
    country_value: 'GH',
  },
  {
    country: 'Gambia',
    country_value: 'GM',
  },
  {
    country: 'Guinea',
    country_value: 'GN',
  },
  {
    country: 'Equatorial Guinea',
    country_value: 'GQ',
  },
  {
    country: 'Greece',
    country_value: 'GR',
  },
  {
    country: 'Guatemala',
    country_value: 'GT',
  },
  {
    country: 'Guinea-Bissau',
    country_value: 'GW',
  },
  {
    country: 'Guyana',
    country_value: 'GY',
  },
  {
    country: 'Honduras',
    country_value: 'HN',
  },
  {
    country: 'Croatia',
    country_value: 'HR',
  },
  {
    country: 'Haiti',
    country_value: 'HT',
  },
  {
    country: 'Hungary',
    country_value: 'HU',
  },
  {
    country: 'Indonesia',
    country_value: 'ID',
  },
  {
    country: 'Ireland',
    country_value: 'IE',
  },
  {
    country: 'Israel',
    country_value: 'IL',
  },
  {
    country: 'India',
    country_value: 'IN',
  },
  {
    country: 'Iraq',
    country_value: 'IQ',
  },
  {
    country: 'Iran',
    country_value: 'IR',
  },
  {
    country: 'Iceland',
    country_value: 'IS',
  },
  {
    country: 'Italy',
    country_value: 'IT',
  },
  {
    country: 'Jamaica',
    country_value: 'JM',
  },
  {
    country: 'Jordan',
    country_value: 'JO',
  },
  {
    country: 'Japan',
    country_value: 'JP',
  },
  {
    country: 'Kenya',
    country_value: 'KE',
  },
  {
    country: 'Kyrgyzstan',
    country_value: 'KG',
  },
  {
    country: 'Cambodia',
    country_value: 'KH',
  },
  {
    country: 'North Korea',
    country_value: 'KP',
  },
  {
    country: 'South Korea',
    country_value: 'KR',
  },
  {
    country: 'Kuwait',
    country_value: 'KW',
  },
  {
    country: 'Kazakhstan',
    country_value: 'KZ',
  },
  {
    country: 'Lao People’s Democratic Republic',
    country_value: 'LA',
  },
  {
    country: 'Lebanon',
    country_value: 'LB',
  },
  {
    country: 'Sri Lanka',
    country_value: 'LK',
  },
  {
    country: 'Liberia',
    country_value: 'LR',
  },
  {
    country: 'Lesotho',
    country_value: 'LS',
  },
  {
    country: 'Lithuania',
    country_value: 'LT',
  },
  {
    country: 'Luxembourg',
    country_value: 'LU',
  },
  {
    country: 'Latvia',
    country_value: 'LV',
  },
  {
    country: 'Libya',
    country_value: 'LY',
  },
  {
    country: 'Morocco',
    country_value: 'MA',
  },
  {
    country: 'Moldova',
    country_value: 'MD',
  },
  {
    country: 'Montenegro',
    country_value: 'ME',
  },
  {
    country: 'Madagascar',
    country_value: 'MG',
  },
  {
    country: 'Macedonia',
    country_value: 'MK',
  },
  {
    country: 'Mali',
    country_value: 'ML',
  },
  {
    country: 'Myanmar',
    country_value: 'MM',
  },
  {
    country: 'Mongolia',
    country_value: 'MN',
  },
  {
    country: 'Mauritania',
    country_value: 'MR',
  },
  {
    country: 'Malawi',
    country_value: 'MW',
  },
  {
    country: 'Mexico',
    country_value: 'MX',
  },
  {
    country: 'Malaysia',
    country_value: 'MY',
  },
  {
    country: 'Mozambique',
    country_value: 'MZ',
  },
  {
    country: 'Namibia',
    country_value: 'NA',
  },
  {
    country: 'New Caledonia',
    country_value: 'NC',
  },
  {
    country: 'Niger',
    country_value: 'NE',
  },
  {
    country: 'Nigeria',
    country_value: 'NG',
  },
  {
    country: 'Nicaragua',
    country_value: 'NI',
  },
  {
    country: 'Netherlands',
    country_value: 'NL',
  },
  {
    country: 'Norway',
    country_value: 'NO',
  },
  {
    country: 'Nepal',
    country_value: 'NP',
  },
  {
    country: 'New Zealand',
    country_value: 'NZ',
  },
  {
    country: 'Oman',
    country_value: 'OM',
  },
  {
    country: 'Panama',
    country_value: 'PA',
  },
  {
    country: 'Peru',
    country_value: 'PE',
  },
  {
    country: 'Papua New Guinea',
    country_value: 'PG',
  },
  {
    country: 'Philippines',
    country_value: 'PH',
  },
  {
    country: 'Pakistan',
    country_value: 'PK',
  },
  {
    country: 'Poland',
    country_value: 'PL',
  },
  {
    country: 'Puerto Rico',
    country_value: 'PR',
  },
  {
    country: 'Palestine',
    country_value: 'PS',
  },
  {
    country: 'Portugal',
    country_value: 'PT',
  },
  {
    country: 'Paraguay',
    country_value: 'PY',
  },
  {
    country: 'Qatar',
    country_value: 'QA',
  },
  {
    country: 'Romania',
    country_value: 'RO',
  },
  {
    country: 'Serbia',
    country_value: 'RS',
  },
  {
    country: 'Russia',
    country_value: 'RU',
  },
  {
    country: 'Rwanda',
    country_value: 'RW',
  },
  {
    country: 'Saudi Arabia',
    country_value: 'SA',
  },
  {
    country: 'Solomon Islands',
    country_value: 'SB',
  },
  {
    country: 'Sudan',
    country_value: 'SD',
  },
  {
    country: 'Sweden',
    country_value: 'SE',
  },
  {
    country: 'Slovenia',
    country_value: 'SI',
  },
  {
    country: 'Svalbard and Jan Mayen',
    country_value: 'SJ',
  },
  {
    country: 'Slovakia',
    country_value: 'SK',
  },
  {
    country: 'Sierra Leone',
    country_value: 'SL',
  },
  {
    country: 'Senegal',
    country_value: 'SN',
  },
  {
    country: 'Somalia',
    country_value: 'SO',
  },
  {
    country: 'Suriname',
    country_value: 'SR',
  },
  {
    country: 'South Sudan',
    country_value: 'SS',
  },
  {
    country: 'El Salvador',
    country_value: 'SV',
  },
  {
    country: 'Syria',
    country_value: 'SY',
  },
  {
    country: 'Eswatini',
    country_value: 'SZ',
  },
  {
    country: 'Chad',
    country_value: 'TD',
  },
  {
    country: 'French Southern Territories',
    country_value: 'TF',
  },
  {
    country: 'Togo',
    country_value: 'TG',
  },
  {
    country: 'Thailand',
    country_value: 'TH',
  },
  {
    country: 'Tajikistan',
    country_value: 'TJ',
  },
  {
    country: 'Timor-Leste',
    country_value: 'TL',
  },
  {
    country: 'Turkmenistan',
    country_value: 'TM',
  },
  {
    country: 'Tunisia',
    country_value: 'TN',
  },
  {
    country: 'Turkey',
    country_value: 'TR',
  },
  {
    country: 'Trinidad and Tobago',
    country_value: 'TT',
  },
  {
    country: 'Taiwan',
    country_value: 'TW',
  },
  {
    country: 'Tanzania',
    country_value: 'TZ',
  },
  {
    country: 'Ukraine',
    country_value: 'UA',
  },
  {
    country: 'Uganda',
    country_value: 'UG',
  },
  {
    country: 'United States of America',
    country_value: 'US',
  },
  {
    country: 'Uruguay',
    country_value: 'UY',
  },
  {
    country: 'Uzbekistan',
    country_value: 'UZ',
  },
  {
    country: 'Venezuela',
    country_value: 'VE',
  },
  {
    country: 'Vietnam',
    country_value: 'VN',
  },
  {
    country: 'Vanuatu',
    country_value: 'VU',
  },
  {
    country: 'Kosovo',
    country_value: 'XK',
  },
  {
    country: 'Yemen',
    country_value: 'YE',
  },
  {
    country: 'South Africa',
    country_value: 'ZA',
  },
  {
    country: 'Zambia',
    country_value: 'ZM',
  },
  {
    country: 'Zimbabwe',
    country_value: 'ZW',
  },
];
